# Form implementation generated from reading ui file 'd:\__PRODUCTION__\LIAMOS\LIAMOS_2506_blender_pipeline\07_CODE\ui\_old\PL_logger_v0001.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 926)
        self.wdg_main = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdg_main.sizePolicy().hasHeightForWidth())
        self.wdg_main.setSizePolicy(sizePolicy)
        self.wdg_main.setStyleSheet("background-color: #414752;")
        self.wdg_main.setObjectName("wdg_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wdg_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frm_top_logger = QtWidgets.QFrame(parent=self.wdg_main)
        self.frm_top_logger.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frm_top_logger.setStyleSheet("")
        self.frm_top_logger.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frm_top_logger.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frm_top_logger.setObjectName("frm_top_logger")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frm_top_logger)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frm_logo_pipeliam = QtWidgets.QFrame(parent=self.frm_top_logger)
        self.frm_logo_pipeliam.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frm_logo_pipeliam.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frm_logo_pipeliam.setObjectName("frm_logo_pipeliam")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frm_logo_pipeliam)
        self.verticalLayout_4.setContentsMargins(-1, 20, -1, 20)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_logo_pipeliam = QtWidgets.QPushButton(parent=self.frm_logo_pipeliam)
        self.btn_logo_pipeliam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_logo_pipeliam.setStyleSheet("background-color:transparent;")
        self.btn_logo_pipeliam.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo/logo_green.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_logo_pipeliam.setIcon(icon)
        self.btn_logo_pipeliam.setIconSize(QtCore.QSize(150, 150))
        self.btn_logo_pipeliam.setDefault(False)
        self.btn_logo_pipeliam.setFlat(True)
        self.btn_logo_pipeliam.setObjectName("btn_logo_pipeliam")
        self.verticalLayout_4.addWidget(self.btn_logo_pipeliam)
        self.lab_login = QtWidgets.QLabel(parent=self.frm_logo_pipeliam)
        font = QtGui.QFont()
        font.setFamily("TrendSansW00-One")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.lab_login.setFont(font)
        self.lab_login.setStyleSheet("color :#37ad74")
        self.lab_login.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.lab_login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lab_login.setObjectName("lab_login")
        self.verticalLayout_4.addWidget(self.lab_login)
        self.horizontalLayout_3.addWidget(self.frm_logo_pipeliam)
        self.verticalLayout.addWidget(self.frm_top_logger)
        self.frame_main_logger = QtWidgets.QFrame(parent=self.wdg_main)
        self.frame_main_logger.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_main_logger.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_main_logger.setObjectName("frame_main_logger")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main_logger)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frm_login_content = QtWidgets.QFrame(parent=self.frame_main_logger)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frm_login_content.sizePolicy().hasHeightForWidth())
        self.frm_login_content.setSizePolicy(sizePolicy)
        self.frm_login_content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frm_login_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_login_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_login_content.setObjectName("frm_login_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_login_content)
        self.verticalLayout_3.setContentsMargins(60, -1, 60, -1)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lie_username = QtWidgets.QLineEdit(parent=self.frm_login_content)
        self.lie_username.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lie_username.sizePolicy().hasHeightForWidth())
        self.lie_username.setSizePolicy(sizePolicy)
        self.lie_username.setMinimumSize(QtCore.QSize(200, 100))
        self.lie_username.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("TrendSansW00-One")
        font.setPointSize(20)
        self.lie_username.setFont(font)
        self.lie_username.setStyleSheet("border : none;\n"
"border-bottom : 2px solid #37ad74;\n"
"color : #FFF;\n"
"padding-bottom : 5px")
        self.lie_username.setObjectName("lie_username")
        self.verticalLayout_3.addWidget(self.lie_username)
        self.lie_password = QtWidgets.QLineEdit(parent=self.frm_login_content)
        self.lie_password.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("TrendSansW00-One")
        font.setPointSize(20)
        self.lie_password.setFont(font)
        self.lie_password.setStyleSheet("border : none;\n"
"border-bottom : 2px solid #37ad74;\n"
"color : #FFF;\n"
"padding-bottom : 5px")
        self.lie_password.setInputMask("")
        self.lie_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lie_password.setObjectName("lie_password")
        self.verticalLayout_3.addWidget(self.lie_password)
        self.pushButton = QtWidgets.QPushButton(parent=self.frm_login_content)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("TrendSansW00-One")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:#37ad74;\n"
"    color:#414752;\n"
"    border-radius:7px;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color:#FFF;\n"
"    background-color:#000000;\n"
"}")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.chb_remember = QtWidgets.QCheckBox(parent=self.frm_login_content)
        font = QtGui.QFont()
        font.setFamily("TrendSansW00-One")
        font.setPointSize(16)
        self.chb_remember.setFont(font)
        self.chb_remember.setStyleSheet("QCheckBox{\n"
"    color:#FFF;\n"
"    background-color:transparent;\n"
"    border:none\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    color :#37ad74;\n"
"}\n"
"")
        self.chb_remember.setCheckable(True)
        self.chb_remember.setChecked(True)
        self.chb_remember.setAutoRepeat(False)
        self.chb_remember.setTristate(False)
        self.chb_remember.setObjectName("chb_remember")
        self.verticalLayout_3.addWidget(self.chb_remember)
        self.frm_forgotten_pwd = QtWidgets.QFrame(parent=self.frm_login_content)
        self.frm_forgotten_pwd.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frm_forgotten_pwd.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_forgotten_pwd.setObjectName("frm_forgotten_pwd")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frm_forgotten_pwd)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lab_forgotten_pwd = QtWidgets.QLabel(parent=self.frm_forgotten_pwd)
        font = QtGui.QFont()
        font.setFamily("TrendSansW00-One")
        font.setPointSize(12)
        self.lab_forgotten_pwd.setFont(font)
        self.lab_forgotten_pwd.setStyleSheet("color :#37ad74")
        self.lab_forgotten_pwd.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lab_forgotten_pwd.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lab_forgotten_pwd.setOpenExternalLinks(True)
        self.lab_forgotten_pwd.setObjectName("lab_forgotten_pwd")
        self.verticalLayout_5.addWidget(self.lab_forgotten_pwd)
        self.verticalLayout_3.addWidget(self.frm_forgotten_pwd)
        self.verticalLayout_2.addWidget(self.frm_login_content)
        self.frm_infos = QtWidgets.QFrame(parent=self.frame_main_logger)
        self.frm_infos.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frm_infos.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_infos.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_infos.setObjectName("frm_infos")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frm_infos)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.frm_infos)
        font = QtGui.QFont()
        font.setFamily("TrendSansW00-One")
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setStyleSheet("color :#37ad74")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frm_infos)
        self.verticalLayout.addWidget(self.frame_main_logger)
        MainWindow.setCentralWidget(self.wdg_main)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_login.setText(_translate("MainWindow", "Log in"))
        self.lie_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lie_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Log In"))
        self.chb_remember.setText(_translate("MainWindow", "Keep me logged in"))
        self.lab_forgotten_pwd.setText(_translate("MainWindow", "Forgot your password ?"))
        self.label.setText(_translate("MainWindow", "All rights reserved to Liamos Prod© 2025"))
